//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-146 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.15 at 01:00:01 PM CET 
//


package work;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExpFkXmlQueryElemXO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExpFkXmlQueryElemXO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="from" type="{}ExpFkXmlQueryElemPartXO" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="select" type="{}StrExpFkXO" minOccurs="0"/>
 *         &lt;element name="where" type="{}StrExpFkXO" minOccurs="0"/>
 *         &lt;element name="group" type="{}StrExpFkXO" minOccurs="0"/>
 *         &lt;element name="having" type="{}StrExpFkXO" minOccurs="0"/>
 *         &lt;element name="ordered" type="{}StrExpFkXO" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExpFkXmlQueryElemXO", propOrder = {
    "from",
    "select",
    "where",
    "group",
    "having",
    "ordered"
})
public class ExpFkXmlQueryElemXO {

    protected List<ExpFkXmlQueryElemPartXO> from;
    protected StrExpFkXO select;
    protected StrExpFkXO where;
    protected StrExpFkXO group;
    protected StrExpFkXO having;
    protected StrExpFkXO ordered;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "name")
    protected String name;

    /**
     * Gets the value of the from property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the from property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFrom().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExpFkXmlQueryElemPartXO }
     * 
     * 
     */
    public List<ExpFkXmlQueryElemPartXO> getFrom() {
        if (from == null) {
            from = new ArrayList<ExpFkXmlQueryElemPartXO>();
        }
        return this.from;
    }

    /**
     * Gets the value of the select property.
     * 
     * @return
     *     possible object is
     *     {@link StrExpFkXO }
     *     
     */
    public StrExpFkXO getSelect() {
        return select;
    }

    /**
     * Sets the value of the select property.
     * 
     * @param value
     *     allowed object is
     *     {@link StrExpFkXO }
     *     
     */
    public void setSelect(StrExpFkXO value) {
        this.select = value;
    }

    /**
     * Gets the value of the where property.
     * 
     * @return
     *     possible object is
     *     {@link StrExpFkXO }
     *     
     */
    public StrExpFkXO getWhere() {
        return where;
    }

    /**
     * Sets the value of the where property.
     * 
     * @param value
     *     allowed object is
     *     {@link StrExpFkXO }
     *     
     */
    public void setWhere(StrExpFkXO value) {
        this.where = value;
    }

    /**
     * Gets the value of the group property.
     * 
     * @return
     *     possible object is
     *     {@link StrExpFkXO }
     *     
     */
    public StrExpFkXO getGroup() {
        return group;
    }

    /**
     * Sets the value of the group property.
     * 
     * @param value
     *     allowed object is
     *     {@link StrExpFkXO }
     *     
     */
    public void setGroup(StrExpFkXO value) {
        this.group = value;
    }

    /**
     * Gets the value of the having property.
     * 
     * @return
     *     possible object is
     *     {@link StrExpFkXO }
     *     
     */
    public StrExpFkXO getHaving() {
        return having;
    }

    /**
     * Sets the value of the having property.
     * 
     * @param value
     *     allowed object is
     *     {@link StrExpFkXO }
     *     
     */
    public void setHaving(StrExpFkXO value) {
        this.having = value;
    }

    /**
     * Gets the value of the ordered property.
     * 
     * @return
     *     possible object is
     *     {@link StrExpFkXO }
     *     
     */
    public StrExpFkXO getOrdered() {
        return ordered;
    }

    /**
     * Sets the value of the ordered property.
     * 
     * @param value
     *     allowed object is
     *     {@link StrExpFkXO }
     *     
     */
    public void setOrdered(StrExpFkXO value) {
        this.ordered = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
