//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.16 at 05:25:00 PM CET 
//


package work;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import work.marshalling.ContentXMLAbstract;


/**
 * <p>Java class for ExpFkXmlQueryXO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExpFkXmlQueryXO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="elemStr" type="{}ExpFkXmlQueryElemXO"/>
 *         &lt;element name="elemBud" type="{}ExpFkXmlQueryElemXO" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="elemWart" type="{}ExpFkXmlQueryElemXO" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="elemMag" type="{}ExpFkXmlQueryElemXO" minOccurs="0"/>
 *         &lt;element name="elemDok" type="{}ExpFkXmlQueryElemXO" minOccurs="0"/>
 *         &lt;element name="elemTyp" type="{}ExpFkXmlQueryElemXO" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExpFkXmlQueryXO", propOrder = {
    "elemStr",
    "elemBud",
    "elemWart",
    "elemMag",
    "elemDok",
    "elemTyp"
})
public class ExpFkXmlQueryXO extends ContentXMLAbstract{

    @XmlElement(required = true)
    protected ExpFkXmlQueryElemXO elemStr;
    protected List<ExpFkXmlQueryElemXO> elemBud;
    protected List<ExpFkXmlQueryElemXO> elemWart;
    protected ExpFkXmlQueryElemXO elemMag;
    protected ExpFkXmlQueryElemXO elemDok;
    protected List<ExpFkXmlQueryElemXO> elemTyp;

    /**
     * Gets the value of the elemStr property.
     * 
     * @return
     *     possible object is
     *     {@link ExpFkXmlQueryElemXO }
     *     
     */
    public ExpFkXmlQueryElemXO getElemStr() {
        return elemStr;
    }

    /**
     * Sets the value of the elemStr property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExpFkXmlQueryElemXO }
     *     
     */
    public void setElemStr(ExpFkXmlQueryElemXO value) {
        this.elemStr = value;
    }

    /**
     * Gets the value of the elemBud property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the elemBud property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getElemBud().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExpFkXmlQueryElemXO }
     * 
     * 
     */
    public List<ExpFkXmlQueryElemXO> getElemBud() {
        if (elemBud == null) {
            elemBud = new ArrayList<ExpFkXmlQueryElemXO>();
        }
        return this.elemBud;
    }

    /**
     * Gets the value of the elemWart property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the elemWart property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getElemWart().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExpFkXmlQueryElemXO }
     * 
     * 
     */
    public List<ExpFkXmlQueryElemXO> getElemWart() {
        if (elemWart == null) {
            elemWart = new ArrayList<ExpFkXmlQueryElemXO>();
        }
        return this.elemWart;
    }

    /**
     * Gets the value of the elemMag property.
     * 
     * @return
     *     possible object is
     *     {@link ExpFkXmlQueryElemXO }
     *     
     */
    public ExpFkXmlQueryElemXO getElemMag() {
        return elemMag;
    }

    /**
     * Sets the value of the elemMag property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExpFkXmlQueryElemXO }
     *     
     */
    public void setElemMag(ExpFkXmlQueryElemXO value) {
        this.elemMag = value;
    }

    /**
     * Gets the value of the elemDok property.
     * 
     * @return
     *     possible object is
     *     {@link ExpFkXmlQueryElemXO }
     *     
     */
    public ExpFkXmlQueryElemXO getElemDok() {
        return elemDok;
    }

    /**
     * Sets the value of the elemDok property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExpFkXmlQueryElemXO }
     *     
     */
    public void setElemDok(ExpFkXmlQueryElemXO value) {
        this.elemDok = value;
    }

    /**
     * Gets the value of the elemTyp property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the elemTyp property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getElemTyp().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExpFkXmlQueryElemXO }
     * 
     * 
     */
    public List<ExpFkXmlQueryElemXO> getElemTyp() {
        if (elemTyp == null) {
            elemTyp = new ArrayList<ExpFkXmlQueryElemXO>();
        }
        return this.elemTyp;
    }

}
